import { SKILLS } from "./catalog";
import { defaultConnectorStates } from "./connectors";
import type { MoaState } from "./types";

const now = () => Date.now();
const H = 3600_000;

export function createDefaultState(): MoaState {
  const t = now();
  return {
    version: 1,
    user: {
      id: "local-user",
      name: "Victory",
      email: "you@example.com",
      avatarUrl: null,
      // Prototype: the local account owns this instance. A real deployment
      // must derive this from the authenticated session, never from input.
      role: "head",
    },
    identity: {
      mode: "orb",
      pictureUrl: null,
      shape: "circle",
      zoom: 1,
      offsetX: 0,
      offsetY: 0,
      name: "MOA",
    },
    appearance: {
      theme: "dark",
      backgroundMode: "gradient",
      solidColor: "#0f151c",
      gradientFrom: "#0b1016",
      gradientTo: "#123039",
      gradientAngle: 155,
      imageUrl: null,
      imageFit: "cover",
      imagePositionX: 50,
      imagePositionY: 50,
      imageOpacity: 0.6,
      imageBlur: 0,
      preset: "default",
      transparency: 72,
      density: "comfortable",
      fontSize: 16,
      bubbleStyle: "bubble",
      animations: true,
      glow: true,
      reducedMotion: false,
    },
    personality: {
      notes: "Speak plainly. Tell me when something is not possible instead of guessing.",
      tone: "direct",
      verbosity: 40,
      formality: 35,
      proactivity: 60,
      style: "Prefers short answers, concrete next steps, no filler.",
      emojis: false,
    },
    conversations: [
      {
        id: "c-demo-1",
        title: "Demo · MOA capabilities",
        pinned: true,
        createdAt: t - 3 * H,
        updatedAt: t - 2 * H,
        messages: [
          {
            id: "m1",
            role: "user",
            content: "What can you actually do right now?",
            createdAt: t - 3 * H,
          },
          {
            id: "m2",
            role: "system",
            content: "Demo conversation. No model provider is connected in this prototype.",
            createdAt: t - 3 * H + 1000,
            status: "unavailable",
          },
          {
            id: "m3",
            role: "moa",
            content:
              "Right now I can hold structure: conversations, memory, knowledge, files, planner runs and Builder projects all persist locally for you.\n\nWhat I cannot do yet is reach the outside world — web search, maps, voice, email and numbers all need a provider connected first. Every one of those surfaces exists and will tell you exactly what is missing.",
            createdAt: t - 3 * H + 2000,
          },
        ],
      },
    ],
    chatProjects: [
      {
        id: "cp-personal",
        name: "Personal",
        description: "Everyday conversations that are not tied to work.",
        colour: "#4cc9f0",
        instructions: "",
        createdAt: t - 50 * H,
        updatedAt: t - 50 * H,
      },
    ],
    activeConversationId: "c-demo-1",
    memories: [
      {
        id: "mem-1",
        content: "Prefers direct answers with no filler.",
        category: "preference",
        tags: ["communication"],
        importance: 3,
        pinned: true,
        source: "user",
        approved: true,
        createdAt: t - 40 * H,
      },
      {
        id: "mem-2",
        content: "Is building MOA, a modular personal assistant environment.",
        category: "project",
        tags: ["moa", "product"],
        importance: 3,
        pinned: true,
        source: "user",
        approved: true,
        createdAt: t - 30 * H,
      },
      {
        id: "mem-3",
        content: "Works mostly from a phone in the evenings.",
        category: "routine",
        tags: ["mobile"],
        importance: 2,
        pinned: false,
        source: "proposed",
        approved: false,
        createdAt: t - 2 * H,
      },
    ],
    knowledge: [
      {
        id: "k-1",
        title: "MOA product specification",
        type: "note",
        location: "local://notes/moa-spec",
        status: "ready",
        addedAt: t - 20 * H,
        chunks: 42,
        summary: "Demo source. Architecture, skills and status conventions for MOA.",
      },
      {
        id: "k-2",
        title: "telephony-provider-terms.pdf",
        type: "pdf",
        location: "local://uploads/telephony-provider-terms.pdf",
        status: "unavailable",
        addedAt: t - 5 * H,
        chunks: 0,
        summary: "Indexing needs an embedding provider, which is not configured.",
      },
    ],
    files: [
      {
        id: "f-1",
        name: "moa-architecture.pdf",
        size: 482_000,
        kind: "pdf",
        status: "ready",
        addedAt: t - 22 * H,
        note: "Demo file. Stored locally in this prototype.",
      },
      {
        id: "f-2",
        name: "inventory-mockup.png",
        size: 1_240_000,
        kind: "image",
        status: "ready",
        addedAt: t - 8 * H,
        note: "Demo file.",
      },
      {
        id: "f-3",
        name: "expenses-q3.xlsx",
        size: 96_000,
        kind: "spreadsheet",
        status: "unavailable",
        addedAt: t - 4 * H,
        note: "Parsing requires a document processing service.",
      },
    ],
    builderProjects: [
      {
        id: "b-1",
        name: "Inventory App",
        description: "Stock tracking with low-stock alerts and a simple supplier list.",
        technology: "React + TypeScript + Postgres",
        status: "review",
        buildStatus: "passing",
        testStatus: "failing",
        createdAt: t - 26 * H,
        updatedAt: t - H,
        tasks: [
          { id: "t1", title: "Understand requirements", stage: "understand", status: "done" },
          { id: "t2", title: "Decompose into modules", stage: "decompose", status: "done" },
          {
            id: "t3",
            title: "Draft data architecture",
            stage: "architecture",
            status: "done",
            detail: "items, suppliers, stock_movements",
          },
          { id: "t4", title: "Generate item CRUD", stage: "generate", status: "done" },
          {
            id: "t5",
            title: "Run test suite",
            stage: "test",
            status: "failed",
            detail: "2 failing: low-stock threshold boundary",
          },
          { id: "t6", title: "Self review", stage: "review", status: "pending" },
          { id: "t7", title: "User approval", stage: "approve", status: "blocked" },
        ],
        files: [
          {
            path: "src/types/inventory.ts",
            language: "ts",
            change: "added",
            content:
              "export interface Item {\n  id: string;\n  sku: string;\n  name: string;\n  quantity: number;\n  reorderLevel: number;\n}\n",
          },
          {
            path: "src/lib/stock.ts",
            language: "ts",
            change: "added",
            content:
              "import type { Item } from '../types/inventory';\n\nexport const isLowStock = (item: Item) => item.quantity <= item.reorderLevel;\n",
          },
          {
            path: "README.md",
            language: "md",
            change: "modified",
            content: "# Inventory App\n\nDemo project generated inside the MOA Builder prototype.\n",
          },
        ],
        logs: [
          { at: t - 3 * H, level: "info", text: "Plan accepted: 7 tasks" },
          { at: t - 2 * H, level: "info", text: "Generated 3 files" },
          { at: t - H, level: "error", text: "Test run failed: 2 assertions" },
        ],
        proposal: {
          summary: "Add low-stock alerting to the items module",
          rationale:
            "Reorder level exists on the model but nothing surfaces it. Adds a derived flag plus a dashboard strip.",
          files: ["src/lib/stock.ts", "src/components/LowStockStrip.tsx"],
          decision: "pending",
        },
      },
    ],
    plannerRuns: [
      {
        id: "p-1",
        goal: "Create an inventory application",
        createdAt: t - 26 * H,
        status: "blocked",
        steps: [
          { id: "s1", title: "Clarify requirements", status: "done", result: "3 modules identified" },
          { id: "s2", title: "Design architecture", tool: "builder", status: "done" },
          { id: "s3", title: "Generate files", tool: "builder", status: "done", result: "3 files" },
          { id: "s4", title: "Run tests", tool: "code", status: "failed", result: "2 failing tests" },
          { id: "s5", title: "Correct and re-run", tool: "builder", status: "blocked", result: "Needs model provider" },
        ],
      },
    ],
    permissions: [
      { id: "web.access", skill: "Web", label: "Internet access", description: "Let MOA query a search provider and fetch pages.", granted: false, requiresProvider: true },
      { id: "location", skill: "Maps", label: "Location", description: "Use device location for places and directions.", granted: false, requiresProvider: true },
      { id: "microphone", skill: "Voice", label: "Microphone", description: "Capture audio for speech-to-text.", granted: false, requiresProvider: true },
      { id: "email.read", skill: "Email", label: "Read mail", description: "Read messages from an authorised mailbox.", granted: false, requiresProvider: true },
      { id: "email.send", skill: "Email", label: "Send mail", description: "Send on your behalf from an authorised mailbox.", granted: false, requiresProvider: true },
      { id: "files.read", skill: "Files", label: "Read files", description: "Read files you upload to MOA.", granted: true, requiresProvider: false },
      { id: "files.write", skill: "Files", label: "Write files", description: "Create or modify stored files.", granted: true, requiresProvider: false },
      { id: "memory.write", skill: "Memory", label: "Write memory", description: "Propose and store long-term memories.", granted: true, requiresProvider: false },
      { id: "numbers.manage", skill: "Numbers", label: "Manage numbers", description: "Provision and manage numbers via a provider account.", granted: false, requiresProvider: true },
      { id: "comms.send", skill: "Communications", label: "Send messages", description: "Send through authorised channels.", granted: false, requiresProvider: true },
      { id: "code.execute", skill: "Code", label: "Execute code", description: "Run code in a sandbox.", granted: false, requiresProvider: true },
      { id: "builder.files", skill: "Builder", label: "Project files", description: "Read and propose changes to project files.", granted: true, requiresProvider: false },
      { id: "device.control", skill: "Devices", label: "Device control", description: "Send actions to a paired device.", granted: false, requiresProvider: true },
    ],
    accounts: [
      { id: "a-mail", provider: "Mail provider", category: "email", account: null, status: "not configured", scopes: ["mail.read", "mail.send"] },
      { id: "a-maps", provider: "Maps provider", category: "maps", account: null, status: "not configured", scopes: ["places", "directions"] },
      { id: "a-tel", provider: "Telephony provider", category: "numbers", account: null, status: "not configured", scopes: ["numbers.provision", "sms.receive"] },
      { id: "a-model", provider: "Model provider", category: "model", account: null, status: "not configured", scopes: ["chat", "vision"] },
      { id: "a-store", provider: "Object storage", category: "storage", account: null, status: "not configured", scopes: ["files.rw"] },
    ],
    devices: [
      { id: "d-1", name: "This browser", kind: "desktop", status: "unavailable", actions: ["Read clipboard", "Open URL"] },
      { id: "d-2", name: "Android phone", kind: "phone", status: "unavailable", actions: ["Notifications", "Share sheet"] },
    ],
    skills: SKILLS.map((s) => ({ id: s.id, enabled: s.status !== "PLANNED" })),
    model: { activeId: "moa-general", autoRouting: false },
    connectors: defaultConnectorStates(),
    constitution: {
      headUserId: "local-user",
      updatedAt: t,
      rules: [
        { id: "law-1", kind: "law", locked: true, text: "MOA serves the Head and never acts against the Head's stated interest.", createdAt: t },
        { id: "law-2", kind: "law", locked: true, text: "MOA never fabricates a capability, connection or result it does not have.", createdAt: t },
        { id: "law-3", kind: "law", locked: true, text: "MOA never bypasses authentication, verification or another person's consent.", createdAt: t },
        { id: "pr-1", kind: "principle", locked: false, text: "Say plainly what is missing instead of guessing.", createdAt: t },
        { id: "pr-2", kind: "principle", locked: false, text: "Keep each user's identity, memory and connectors isolated.", createdAt: t },
      ],
    },
    location: { sharing: false, permission: "unknown", last: null, shareWithPeople: false },
    lookups: [],
  };
}
